config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :desc, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :desc %>
    <%= f.text_area :desc %>
  </p>
  <p>
    <%= f.label :completed %>
    <%= f.check_box :completed %>
  </p>
  <%= f.submit %>
<% end %>

app/views/tasks/_form_new.html.erb
<%= form_for @task do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :desc %>
    <%= f.text_area :desc %>
  </p>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<ul>
  <% @tasks.each do |task|%>
  <li>
    <h2><%= link_to task.title, task_path(task) %></h2>
    <p><%= task.desc %></p>
    <h3>
      <%= link_to 'edit', edit_task_path(task) %>
      <%= link_to 'delete', task_path(task), method: :delete %>
    </h3>
  </li>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<h1>Tasks#new</h1>

<%= render 'form_new' %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.desc %></p>
<p>
  <% if @task.completed %>
    <%= "completed" %>
    <input type="checkbox" checked>
  <% else %>
    <%= "uncompleted" %>
    <input type="checkbox">
  <% end %>
</p>
<p>
  <%= link_to 'Back', tasks_path %>
</p>